# ===============================
# = DATABASE CONFIG
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/your_database
spring.datasource.username=your_username
spring.datasource.password=your_password

# ===============================
# = JPA CONFIGURATION
# ===============================
spring.jpa.show-sql=true

# ===============================
# = HIBERNATE CONFIGURATION
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# = MAPPER CONFIGURATION
# ===============================
br.com.treinaweb.twprojects.mappers.provider=modelmapper

# ===============================
# = LOGGING
# ===============================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
